
name: CD

on:
  workflow_run:
    workflows: ["CI for HVT Nearest ATF"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      args: --severity-threshold=high

  release-please:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
         
    steps:
       - name: Run Release-Please
         id: release
         uses: googleapis/release-please-action@v4
         with:
            target-branch: ${{ github.ref_name }}

  
  push-artefacts-s3:
    needs: [release-please]
    name: Push Artefacts
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' && needs.release-please.outputs.release_created == 'true' }}
    strategy:
      matrix:
        env: [DEV,INT]
    environment: ${{ matrix.env }}
    steps:
      - name: Download build artefact
        uses: actions/download-artifact@v4
        with:
          name: build-artefact

      - name: Rename artefact with git tag
        run: |
          mv artefact.zip release-${{ needs.release-please.outputs.tag_name }}.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Push artefact to S3
        run: |
          aws s3 cp release-${{ needs.release-please.outputs.tag_name }}.zip s3://${{ secrets[format('S3_BUCKET_{0}', matrix.env)] }}/
    
            