name: CI for HVT Nearest ATF

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    uses: dvsa/.github/.github/workflows/nodejs-lint.yaml@v5.0.3
    with:
      node-version: '20.x'
  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v5.0.3
    with:
      node-version: '20.x'

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v5.0.3
  
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-names:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      short_sha: ${{ steps.sha.outputs.SHORT_SHA }}
      pretty_branch_name: ${{ steps.branch.outputs.NAME }}
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set short sha output
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short=11 HEAD)" >> $GITHUB_OUTPUT
      - name: Set archive name output
        id: branch
        run: |
          export PRETTY_BRANCH_NAME=$(tr '/' '-' <<< "$BRANCH_NAME")
          echo "NAME=${PRETTY_BRANCH_NAME}" >> $GITHUB_OUTPUT

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v5.0.3
    needs: [ build-names ]
    with:
      upload-artifact: true
      build-folder: dist/artefact.zip
      build-command: npm run build:prod
      node-version: '20.x'

